# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - revolute_shoulder_1
      - revolute_shoulder_2
      - revolute_upper
      - revolute_elbow
      - revolute_forearm
      - revolute_wrist
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_group_controller:
  ros__parameters:
    joints:
      - revolute_finger_1a
      - revolute_finger_2a
      - revolute_thumb
      - revolute_finger_3a
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity