# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    end_effector_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - revolute_1
      - revolute_2
      - revolute_3
      - revolute_4
      - revolute_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
end_effector_controller:
  ros__parameters:
    joints:
      - revolute_6
      - revolute_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity